config/routes.rb
Rails.application.routes.draw do
  
  resources :contents
  devise_for :users
  root 'pages#home'
  
  get 'about' => 'pages#about'

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titolo %><br>
    <%= f.text_field :titolo %>
  </div>
  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contents</h1>

<table>
  <thead>
    <tr>
      <th>Titolo</th>
      <th>Descrizione</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.titolo %></td>
        <td><%= content.descrizione %></td>
        <td><%= content.price %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titolo:</strong>
  <%= @content.titolo %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @content.descrizione %>
</p>

<p>
  <strong>Price:</strong>
  <%= @content.price %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer grey lighten-1">
        <div class="footer-copyright">
        <div class="container">
          <div class="row">

              <div class="col s4">
                 © 2016 EVG Motorsport
              </div>

              <div class="col s4">
                  Social
              </div>

              <div class="col s4">
                  <%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
              </div>

          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<!-- Navbar -->

<header class="navbar-fixed">

<!-- Dropdown Structure -->
	<ul id="dropdown1" class="dropdown-content">
	  <li><a href="#!">one</a></li>
	  <li><a href="#!">two</a></li>
	  <li class="divider"></li>
	  <li><a href="#!">three</a></li>
	</ul>	

	<nav class="white">
	  <div class="container nav-wrapper">
	    <%= link_to "Home", root_path, class: "black-text brand-logo"  %>
	    	<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="black-text material-icons">menu</i></a>
		    <ul class="right hide-on-med-and-down">
			      <% if user_signed_in? %>
			      	<li><%= link_to "Log out", destroy_user_session_path, class: "black-text", method: :delete %></li>
			      <% else %>
			        <li><%= link_to "Log in", new_user_session_path, class: "black-text"  %></li>
		   	     <li><%= link_to "Sign in", new_user_registration_path, class: "black-text"  %></li>
			      <% end %>
		    </ul>
		    <ul class="side-nav" id="mobile-demo">
			    <% if user_signed_in? %>
			    	<li><%= link_to "Log out", destroy_user_session_path, class: "black-text", method: :delete %></li>
			    <% else %>
			        <li><%= link_to "Log in", new_user_session_path, class: "black-text"  %></li>
		   	        <li><%= link_to "Sign in", new_user_registration_path, class: "black-text"  %></li>
			    <% end %>
	   		</ul>
	  </div>
	</nav>
</header>

<!-- End Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <title>TestMarket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	      
	<main class="container">    
		<%= yield %>
	</main>

<%= render "layouts/footer" %>

</body>$£

	<script>
	$(".button-collapse").sideNav();
	</script>

</html>

app/views/pages/about.html.erb
<h1>Chi siamo?</h1>
<p>Siamo un team di ragazzi che insegna corsi bla bla bla</p>

app/views/pages/home.html.erb
<h1>Questa è la nostra home</h1>